# Site settings
title: Michael Steward
email: stewardm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
permalink: /:year/:month/:title.html
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaelsteward.com" # the base hostname & protocol for your site
paginate: 10
twitter_username: popdog
github_username:  msteward

# Build settings
markdown: kramdown
